package sv.edu.formas.modelo.entidad;
// Generated May 3, 2023 9:58:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Receta generated by hbm2java
 */
@Entity
@Table(name="receta"
    ,catalog="farmacia"
)
public class Receta  implements java.io.Serializable {


     private Integer idReceta;
     private Usuario usuario;
     private String indicacion;
     private Set recetaxmedicamentos = new HashSet(0);

    public Receta() {
    }

	
    public Receta(Usuario usuario, String indicacion) {
        this.usuario = usuario;
        this.indicacion = indicacion;
    }
    public Receta(Usuario usuario, String indicacion, Set recetaxmedicamentos) {
       this.usuario = usuario;
       this.indicacion = indicacion;
       this.recetaxmedicamentos = recetaxmedicamentos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idReceta", unique=true, nullable=false)
    public Integer getIdReceta() {
        return this.idReceta;
    }
    
    public void setIdReceta(Integer idReceta) {
        this.idReceta = idReceta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUsuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="indicacion", nullable=false, length=65535)
    public String getIndicacion() {
        return this.indicacion;
    }
    
    public void setIndicacion(String indicacion) {
        this.indicacion = indicacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="receta")
    public Set getRecetaxmedicamentos() {
        return this.recetaxmedicamentos;
    }
    
    public void setRecetaxmedicamentos(Set recetaxmedicamentos) {
        this.recetaxmedicamentos = recetaxmedicamentos;
    }




}


