package modelo.entidad;
// Generated Apr 29, 2023 2:29:44 PM by Hibernate Tools 4.3.1


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detfact generated by hbm2java
 */
@Entity
@Table(name="detfact"
    ,catalog="fact"
)
public class Detfact  implements java.io.Serializable {


     private Integer idDet;
     private Factura factura;
     private Producto producto;
     private Integer cantidad;

    public Detfact() {
    }

    public Detfact(Factura factura, Producto producto, Integer cantidad) {
       this.factura = factura;
       this.producto = producto;
       this.cantidad = cantidad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDet", unique=true, nullable=false)
    public Integer getIdDet() {
        return this.idDet;
    }
    
    public void setIdDet(Integer idDet) {
        this.idDet = idDet;
    }

@ManyToOne(fetch=FetchType.LAZY) //tiene una dependencia directa, por tanto necesita cascada
    @JoinColumn(name="noFactura")
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }

@ManyToOne(fetch=FetchType.LAZY, cascade =CascadeType.ALL) //si no hay producto, pues que lo inserte
    @JoinColumn(name="idProducto")
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    
    @Column(name="cantidad")
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


