package modelo.entidad;
// Generated Apr 29, 2023 2:29:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,catalog="fact"
)
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private String nomProducto;
     private Set<Detfact> detfacts = new HashSet(0);

    public Producto() {
    }

    //no se requiere el set aca
    public Producto(String nomProducto) {
       this.nomProducto = nomProducto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idProducto", unique=true, nullable=false)
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }

    
    @Column(name="nomProducto", length=100)
    public String getNomProducto() {
        return this.nomProducto;
    }
    
    public void setNomProducto(String nomProducto) {
        this.nomProducto = nomProducto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set<Detfact> getDetfacts() {
        return this.detfacts;
    }
    
    public void setDetfacts(Set<Detfact> detfacts) {
        this.detfacts = detfacts;
    }




}


